[h5ESMonitors]
192.168.167.120 name=h5-es-monitors-master001 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.168 name=h5-es-monitors-master002 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.239 name=h5-es-monitors-master003 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.234 name=h5-es-monitors-coordinate001 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.175 name=h5-es-monitors-coordinate002 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.204 name=h5-es-monitors-coordinate003 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.31 name=h5-es-monitors-date001 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.172 name=h5-es-monitors-date002 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.209 name=h5-es-monitors-date003 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.141 name=h5-es-monitors-ingest001 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.235 name=h5-es-monitors-ingest002 ansible_ssh_pass="sdqc#2019#cqds"
192.168.167.123 name=h5-es-monitors-ingest003 ansible_ssh_pass="sdqc#2019#cqds"

#settle es
[settleESMonitors]
192.168.135.54 name=settle-es-monitors-master001 ansible_ssh_pass="Suncar#2020"
192.168.135.194 name=settle-es-monitors-master002 ansible_ssh_pass="Suncar#2020"
192.168.135.223 name=settle-es-monitors-master003 ansible_ssh_pass="Suncar#2020"
