- hosts: settleESMonitors
  gather_facts: no
  vars:
    port: 9114
  tasks:
  - name: 推送二进制文件
    unarchive: src=elasticsearch_exporter-1.1.0.linux-amd64.tar.gz dest=/usr/local
  - name: 重命名
    shell: |
         cd /usr/local
         if [ ! -d elasticsearch_exporter ];then
             mv elasticsearch_exporter-1.1.0.linux-amd64 elasticsearch_exporter
         fi
#  - name: 添加防火墙规则
#    iptables: chain=INPUT protocol=tcp match=tcp destination_port={{ port }} jump=ACCEPT action=insert
#  - name: 把防火墙规则加入到配置文件
#    shell: |
#         iptables-save > /etc/sysconfig/iptables
  - name: 配置systemd文件
    shell: |
         cd /usr/lib/systemd/system
         cat <<EOF> /usr/lib/systemd/system/elasticsearch_exporter.service
         [Unit]
         Description=es_exporter
         [Service]
         ExecStart=/usr/local/elasticsearch_exporter/elasticsearch_exporter --es.uri=http://elastic:shengda2021@{{ inventory_hostname }}:9200 --web.listen-address={{ inventory_hostname }}:9114
         ExecReload=/bin/kill -HUP $MAINPID
         KillMode=process
         Restart=on-failure
         [Install]
         WantedBy=multi-user.target
         EOF
  - name: 启动elasticsearch_exporter服务
    systemd: name=elasticsearch_exporter.service state=restarted enabled=yes daemon_reload=yes
  - name: 推送注册脚本
    copy: src=consul-register.sh dest=/usr/local/bin/
  - name: 注册当前节点   
    # 服务名 实例名 IP 端口 
    shell: /bin/bash /usr/local/bin/consul-register.sh {{ group_names[0] }} {{ name }} {{ inventory_hostname }} {{ port }}    
